### ISSUE TITLE
[BUG] 5e 3.x chat card enrichment breaks attack chat cards

### ISSUE THREAD

**Issue by Shambles1337** [daft-develop/mob-attack-tool#6]
Hi there, posting my screenshots from the issue I raised over at https://github.com/Stendarpaval/mob-attack-tool/issues/61#issuecomment-2064661559. 

Here are my settings (Same as yours far as I can tell)
![Screenshot 2024-04-18 212101](https://github.com/daft-develop/mob-attack-tool/assets/43241871/9ccaa693-a332-4a5c-926a-0294a505908d)

The tool appears and I can increase/decrease the number in the mob and verify the target, as well as make the attack with advantage but when I click the "Mob Attack" button, the attack never resolves.
![Screenshot 2024-04-18 212651](https://github.com/daft-develop/mob-attack-tool/assets/43241871/d5373435-8f27-4d06-a8de-f0be35c45095)

Pasting a screenshot of my chat too, but it just shows the initiative no attacks.
![Screenshot 2024-04-18 212512](https://github.com/daft-develop/mob-attack-tool/assets/43241871/9d4df5ca-a6c8-4f23-9f0d-6090a81f4a1e)

**Comment by daft-develop** [comment]
Thanks for adding the screenshots. I agree it looks like all your settings are the same, but slightly different buggy behaviour. I see from the screen shot you're using Command vs Control for disadvantage, assuming a Mac? I'm testing on Edge, Chrome, and Firefox for Windows and none are exactly like you're seeing. Despite that, I suspect you're seeing whatever bug I see as well, just showing up a little different.

For completeness, can you confirm you're running D&D 5e 3.1.2 and Mob Attack 0.5.0?

If you've got some time, can you try opening a developer console on your browser (it may take a few steps in Safari) and see if it reports any errors when you try to make a Mob attack? You might get some warnings about data.data being depreciated, but I'm expecting some sort of error that mentions '_formula'.
![image](https://github.com/daft-develop/mob-attack-tool/assets/59496570/610b5813-1633-4d9a-a0e0-4dd8bfde1421)

If you're getting a different kind of error, it may be something unrelated. Either way, I'll let you know once I've posted a new release to fix the issue I see, and we can test if that resolves your issue at the same time.

**Comment by Shambles1337** [comment]
So to confirm I am running D&D 5e 3.1.2 and Mob Attack 0.5.0.
Also, I'm not on a Mac, it's a windows PC, but I think the reason it looks different is because I'm not actually using the browser, I am running the game directly using the Foundry VTT client. I did test in Chrome, Edge, and Firefox and it was not working in any browser though.

Also, I have an update, I was able to get mob attack tool to work (I think mostly). I noticed when I went back to my original world, that I'm running my campaign in, another mod wasn't working despite it being the most up to date version. What I did was Uninstall the client, all my mods, installed an earlier version (Version 9, which my buddy has installed and is working) as well as an older version of D&D 5e (I didn't think to write down the version) reinstalled mob attack tool (version 0.3.13). I confirmed it was working. I installed the other mod that wasn't working as well (Dice so Nice) and then I uninstalled V9 of Foundry VTT and installed the newest version of 5e, updated the mods, and installed the newest manifest for Mob attack tool (0.5.0) and Dice So Nice and both are now working (mostly, see below).

I am working on slowly re-introducing my other previously installed mods one by one and testing everything to ensure I don't break anything in the process. 

I am not able to see the attack rolls now for some reason, but it resolves the attacks now, so the mod is at least usable.
![Screenshot 2024-04-19 130203](https://github.com/daft-develop/mob-attack-tool/assets/43241871/78f02339-b04e-4247-a031-23220cd3a82a)

**Comment by daft-develop** [comment]
Thank you for the update. Not sure why the whole re-install was necessary either, but now it sounds like your error is identical to the one I see. Some of the changes in the 5e system from 3.x onward try to "enrich" the chat cards for dice rolls, but the way MAT currently generates the attack card conflicts with some of the system assumptions. I'll have to rework how the attack cards are generated to resolve it, but it is reproducible so it should be something I can resolve _relatively_ quickly.

**Comment by daft-develop** [comment]
@Shambles1337 I've just pushed a new release where I think the issue has been fixed. I did a quick test on Foundry v10, v11 with 5e 2.x, and v11 with 5e 3.1.2 and all are showing the attack cards correctly. Also tested with Dice So Nice and MidiQoL very briefly and it appears to be working with both as well. Please give it a test and let me know if you find any other issues related to this (add as a note) or any new bug I've introduced (please feed to create a new ticket.)

**Comment by Shambles1337** [comment]
The new version works beautifully! Thank you so much!
